use super::endpoints::{ALL, AuthClass, HttpMethod};

type EndpointContract = (&'static str, HttpMethod, &'static str, AuthClass);

const EXPECTED: [EndpointContract; 33] = [
    (
        "request_otp",
        HttpMethod::Post,
        "/api/v2/Trading/GetOTP",
        AuthClass::None,
    ),
    (
        "new_order",
        HttpMethod::Post,
        "/api/v2/Trading/NewOrder",
        AuthClass::Write,
    ),
    (
        "modify_order",
        HttpMethod::Post,
        "/api/v2/Trading/ModifyOrder",
        AuthClass::Write,
    ),
    (
        "cancel_order",
        HttpMethod::Post,
        "/api/v2/Trading/CancelOrder",
        AuthClass::Write,
    ),
    (
        "derivative_new_order",
        HttpMethod::Post,
        "/api/v2/Trading/derNewOrder",
        AuthClass::Write,
    ),
    (
        "derivative_modify_order",
        HttpMethod::Post,
        "/api/v2/Trading/derModifyOrder",
        AuthClass::Write,
    ),
    (
        "derivative_cancel_order",
        HttpMethod::Post,
        "/api/v2/Trading/derCancelOrder",
        AuthClass::Write,
    ),
    (
        "stock_account_balance",
        HttpMethod::Get,
        "/api/v2/Trading/cashAcctBal",
        AuthClass::Read,
    ),
    (
        "derivative_account_balance",
        HttpMethod::Get,
        "/api/v2/Trading/derivAcctBal",
        AuthClass::Read,
    ),
    (
        "ppmmr_account",
        HttpMethod::Get,
        "/api/v2/Trading/ppmmraccount",
        AuthClass::Read,
    ),
    (
        "stock_position",
        HttpMethod::Get,
        "/api/v2/Trading/stockPosition",
        AuthClass::Read,
    ),
    (
        "derivative_position",
        HttpMethod::Get,
        "/api/v2/Trading/derivPosition",
        AuthClass::Read,
    ),
    (
        "max_buy_quantity",
        HttpMethod::Get,
        "/api/v2/Trading/maxBuyQty",
        AuthClass::Read,
    ),
    (
        "max_sell_quantity",
        HttpMethod::Get,
        "/api/v2/Trading/maxSellQty",
        AuthClass::Read,
    ),
    (
        "order_history",
        HttpMethod::Get,
        "/api/v2/Trading/orderHistory",
        AuthClass::Read,
    ),
    (
        "order_book",
        HttpMethod::Get,
        "/api/v2/Trading/orderBook",
        AuthClass::Read,
    ),
    (
        "audit_order_book",
        HttpMethod::Get,
        "/api/v2/Trading/auditOrderBook",
        AuthClass::Read,
    ),
    (
        "rate_limit",
        HttpMethod::Get,
        "/api/v2/Trading/rateLimit",
        AuthClass::Read,
    ),
    (
        "cash_in_advance_amount",
        HttpMethod::Get,
        "/api/v2/cash/cashInAdvanceAmount",
        AuthClass::Read,
    ),
    (
        "unsettled_sold_transaction",
        HttpMethod::Get,
        "/api/v2/cash/unsettleSoldTransaction",
        AuthClass::Read,
    ),
    (
        "cash_transfer_history",
        HttpMethod::Get,
        "/api/v2/cash/transferHistories",
        AuthClass::Read,
    ),
    (
        "cash_in_advance_history",
        HttpMethod::Get,
        "/api/v2/cash/cashInAdvanceHistories",
        AuthClass::Read,
    ),
    (
        "cash_in_advance_estimate",
        HttpMethod::Get,
        "/api/v2/cash/estCashInAdvanceFee",
        AuthClass::Read,
    ),
    (
        "cash_transfer_vsd",
        HttpMethod::Post,
        "/api/v2/cash/vsdCashDW",
        AuthClass::Write,
    ),
    (
        "cash_transfer",
        HttpMethod::Post,
        "/api/v2/cash/transferInternal",
        AuthClass::Write,
    ),
    (
        "create_cash_in_advance",
        HttpMethod::Post,
        "/api/v2/cash/createCashInAdvance",
        AuthClass::Write,
    ),
    (
        "ors_dividend",
        HttpMethod::Get,
        "/api/v2/ors/dividend",
        AuthClass::Read,
    ),
    (
        "ors_exercisable_quantity",
        HttpMethod::Get,
        "/api/v2/ors/exercisableQuantity",
        AuthClass::Read,
    ),
    (
        "ors_history",
        HttpMethod::Get,
        "/api/v2/ors/histories",
        AuthClass::Read,
    ),
    (
        "create_ors",
        HttpMethod::Post,
        "/api/v2/ors/create",
        AuthClass::Write,
    ),
    (
        "stock_transferable",
        HttpMethod::Get,
        "/api/v2/stock/transferable",
        AuthClass::Read,
    ),
    (
        "stock_transfer_history",
        HttpMethod::Get,
        "/api/v2/stock/transferHistories",
        AuthClass::Read,
    ),
    (
        "create_stock_transfer",
        HttpMethod::Post,
        "/api/v2/stock/transfer",
        AuthClass::Write,
    ),
];

#[test]
fn endpoint_table_matches_python_253_public_contract_when_inventory_is_read() {
    // Given
    let expected = EXPECTED;

    // When
    let actual: Vec<_> = ALL
        .iter()
        .map(|endpoint| (endpoint.name, endpoint.method, endpoint.path, endpoint.auth))
        .collect();

    // Then
    assert_eq!(actual, expected);
}
